/**
 * Local Growth Engine — database schema (single source of truth).
 *
 * Design decisions (see README for the full rationale):
 * - Drizzle ORM + PostgreSQL, migrations generated by drizzle-kit.
 * - All IDs are UUID v4 (gen_random_uuid()), snake_case columns, timestamptz.
 * - Enums are enforced with real Postgres ENUM types (pgEnum) — consistent for
 *   every lifecycle/status column, extended by ALTER TYPE in later migrations.
 * - Scores use CHECK constraints (0–100) as a second line of defense beyond the
 *   scoring engines that will be built in later briefs.
 * - One JSONB `provenance` column carries per-field source metadata instead of
 *   one column per field (per master spec).
 * - `metrics.dimension` is jsonb with a unique index over (dimension::text) —
 *   jsonb has no btree opclass in Postgres, and jsonb text output is canonical,
 *   so equality on the text form gives the required uniqueness semantics.
 * - Money is stored as integer minor units (cents) — never floats.
 * - NO raw card or payment data anywhere by design.
 * - `tasks`, `exceptions`, and `audit_logs` use generic entity_type/entity_id
 *   so they can reference any table without fabricating FKs.
 */

import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';

/* ============================================================================
 * ENUMS
 * ========================================================================== */

export const leadLifecycleState = pgEnum('lead_lifecycle_state', [
  'DISCOVERED',
  'ENRICHING',
  'ENRICHED',
  'ANALYZING',
  'ANALYZED',
  'QUALIFIED',
  'REJECTED',
  'DEMO_GENERATING',
  'DEMO_READY',
  'OUTREACH_PENDING',
  'CONTACTED',
  'FOLLOWUP_1',
  'FOLLOWUP_2',
  'RESPONDED',
  'NURTURE',
  'INTERESTED',
  'HOT',
  'SALES_HANDOFF',
  'WON',
  'LOST',
  'DO_NOT_CONTACT',
  'CUSTOMER',
]);

export const websiteStatus = pgEnum('website_status', [
  'NO_WEBSITE',
  'DISCOVERED',
  'SCRAPED',
  'ANALYZED',
  'CRAWL_FAILED',
]);

export const websiteClassification = pgEnum('website_classification', [
  'EXCELLENT',
  'GOOD',
  'AVERAGE',
  'WEAK',
  'VERY_WEAK',
  'NO_WEBSITE',
]);

export const leadClassification = pgEnum('lead_classification', [
  'HIGH_PRIORITY',
  'SECONDARY',
  'REVIEW',
  'REJECT',
]);

export const demoStatus = pgEnum('demo_status', [
  'GENERATING',
  'READY',
  'QA_FAILED',
  'DEPLOYED',
  'EXPIRED',
]);

export const campaignStatus = pgEnum('campaign_status', [
  'DRAFT',
  'ACTIVE',
  'PAUSED',
  'COMPLETED',
]);

export const messageStatus = pgEnum('message_status', [
  'PENDING',
  'SENT',
  'BOUNCED',
  'COMPLAINED',
  'OPENED',
  'CLICKED',
  'REPLIED',
  'OPTED_OUT',
  'FAILED',
]);

export const followupStatus = pgEnum('followup_status', [
  'PENDING',
  'SENT',
  'FAILED',
  'SKIPPED',
]);

export const conversationStatus = pgEnum('conversation_status', [
  'OPEN',
  'HANDLED',
  'CLOSED',
]);

export const messageDirection = pgEnum('message_direction', [
  'INBOUND',
  'OUTBOUND',
]);

// Filled by the reply classifier (a later brief); kept as an enum so the
// schema is explicit, and extended via ALTER TYPE if the classifier needs more.
export const replyClassification = pgEnum('reply_classification', [
  'INTERESTED',
  'NEEDS_INFO',
  'NOT_INTERESTED',
  'OPT_OUT',
  'OTHER',
]);

export const opportunityStatus = pgEnum('opportunity_status', [
  'OPEN',
  'WON',
  'LOST',
]);

export const customerStatus = pgEnum('customer_status', [
  'ACTIVE',
  'PAST_DUE',
  'CANCELLED',
]);

export const onboardingStatus = pgEnum('onboarding_status', [
  'PENDING',
  'SEND_REQUESTED',
  'REQUESTED',
  'COMPLETE',
]);

export const productionWebsiteStatus = pgEnum('production_website_status', [
  'ONBOARDING_COMPLETE',
  'CONTENT_GENERATION',
  'WEBSITE_GENERATION',
  'QA',
  'CUSTOMER_REVIEW',
  'DEPLOYMENT',
  'LIVE',
]);

export const websiteVersionStatus = pgEnum('website_version_status', [
  'DRAFT',
  'QA',
  'DEPLOYED',
  'ROLLED_BACK',
]);

export const domainStatus = pgEnum('domain_status', [
  'AVAILABLE',
  'REGISTERED',
  'IN_USE',
  'EXPIRED',
  'FAILED',
]);

export const subscriptionStatus = pgEnum('subscription_status', [
  'ACTIVE',
  'PAST_DUE',
  'CANCELED',
  'EXPIRED',
]);

export const subscriptionInterval = pgEnum('subscription_interval', [
  'MONTH',
  'YEAR',
]);

export const paymentStatus = pgEnum('payment_status', [
  'PENDING',
  'SUCCEEDED',
  'FAILED',
  'REFUNDED',
]);

export const taskStatus = pgEnum('task_status', [
  'PENDING',
  'RUNNING',
  'SUCCEEDED',
  'FAILED',
  'CANCELED',
]);

export const exceptionPriority = pgEnum('exception_priority', [
  'CRITICAL',
  'HIGH',
  'MEDIUM',
  'LOW',
]);

export const exceptionStatus = pgEnum('exception_status', [
  'OPEN',
  'ACKNOWLEDGED',
  'RESOLVED',
  'IGNORED',
]);

export const scoringType = pgEnum('scoring_type', [
  'WEBSITE_QUALITY',
  'BUSINESS_OPPORTUNITY',
  'LEAD_PRIORITY',
]);

export const templateType = pgEnum('template_type', [
  'DEMO',
  'PRODUCTION_WEB',
]);

export const businessOperationalStatus = pgEnum('business_operational_status', [
  'OPERATIONAL',
  'CLOSED',
  'PERMANENTLY_CLOSED',
  'TEMPORARILY_CLOSED',
  'UNKNOWN',
]);

export const contactStatus = pgEnum('contact_status', [
  'ACTIVE',
  'INVALID',
  'SUPPRESSED',
]);

export const auditActorType = pgEnum('audit_actor_type', [
  'SYSTEM',
  'USER',
  'API',
  'JOB',
]);

/** Why a lead was rejected (recorded per rejection for later analytics).
 *  OPT_OUT / DO_NOT_CONTACT_REQUEST drive the DO_NOT_CONTACT state; the rest
 *  drive REJECTED. */
export const rejectionReason = pgEnum('rejection_reason', [
  'INACTIVE_BUSINESS',
  'NO_CONTACT_ROUTE',
  'OUTSIDE_ICP',
  'EXCELLENT_WEBSITE',
  'LOW_OPPORTUNITY',
  'OPT_OUT',
  'DO_NOT_CONTACT_REQUEST',
  'BAD_DATA',
  'DUPLICATE',
  'OTHER',
]);

/* ============================================================================
 * AUTH — users, refresh-token sessions, and server-side API keys.
 * Exactly ONE owner user exists (bootstrapped from env, no self-signup).
 * API keys are stored hashed (sha256) at rest — the raw key is shown once at
 * creation, never persisted, never exposed to the frontend. Sessions store
 * the refresh-token hash so a stolen DB cannot forge refresh tokens.
 * ========================================================================== */

/** Roles for the authorization matrix. OWNER = full admin; the only user role. */
export const userRole = pgEnum('user_role', ['OWNER']);

/** Remaining auth-only enum. Guarded by OWASP-style validation (KISS). */
export const apiKeyScopeType = pgEnum('api_key_scope', ['read', 'admin']);

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: text('email').notNull(),
    // bcrypt hash — never plaintext. A plaintext email/password is never stored.
    password_hash: text('password_hash').notNull(),
    role: userRole('role').default('OWNER').notNull(),
    is_active: boolean('is_active').default(true).notNull(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    unique('u_users_email').on(t.email),
  ],
);

/** Server-side session records. Only the refresh-token hash is stored. */
export const userSessions = pgTable(
  'user_sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    user_id: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    // sha256 hex of the refresh token — never store the token itself.
    refresh_token_hash: text('refresh_token_hash').notNull(),
    user_agent: text('user_agent'),
    ip_address: text('ip_address'),
    expires_at: timestamp('expires_at', { withTimezone: true }).notNull(),
    revoked_at: timestamp('revoked_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    last_used_at: timestamp('last_used_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    unique('u_user_sessions_refresh_token_hash').on(t.refresh_token_hash),
    index('idx_user_sessions_user_id').on(t.user_id),
  ],
);

/** Server-side API keys for service-to-service calls. Only the sha256 of the
 *  raw key is stored; the raw key is returned exactly once at creation. */
export const apiKeys = pgTable(
  'api_keys',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // Human-readable label, e.g. 'orchestrator-prod'.
    name: text('name').notNull(),
    // Prefix (e.g. 'lge_1a2b3c') shown in the UI for identification; raw key never.
    prefix: text('prefix').notNull(),
    // sha256 hex of the raw key — the only representation kept at rest.
    key_hash: text('key_hash').notNull(),
    scope: apiKeyScopeType('scope').notNull(),
    // Comma-separated service/route identifiers, e.g. 'jobs,scores'.
    allowed_resources: text('allowed_resources'),
    is_active: boolean('is_active').default(true).notNull(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    last_used_at: timestamp('last_used_at', { withTimezone: true }),
    revoked_at: timestamp('revoked_at', { withTimezone: true }),
    expires_at: timestamp('expires_at', { withTimezone: true }),
  },
  (t) => [
    unique('u_api_keys_key_hash').on(t.key_hash),
    unique('u_api_keys_name').on(t.name),
    index('idx_api_keys_prefix').on(t.prefix),
  ],
);

/* ============================================================================
 * SHARED TYPES (documentation of JSONB shapes)
 * ========================================================================== */

/** Per-field source/provenance metadata, e.g.
 *  { phone: { source: 'google_maps', verified_at: '2026-09-02T10:00:00Z' } } */
export type Provenance = Record<string, { source?: string; verified_at?: string; [k: string]: unknown }>;

/** Website quality category scores: conversion 25 / mobile 20 / content 15 /
 *  trust 15 / technical 15 / design_ux 10 (weights live in scoring_versions). */
export type CategoryScores = {
  conversion: number;
  mobile: number;
  content: number;
  trust: number;
  technical: number;
  design_ux: number;
};

/** Formula inputs + weights captured when a lead score was computed. */
export type FormulaFields = {
  inputs: Record<string, number | string | null>;
  weights: Record<string, number>;
};

/* ============================================================================
 * 1. BUSINESSES — the lead/prospect/customer record
 * ========================================================================== */

export const businesses = pgTable(
  'businesses',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_name: text('business_name').notNull(),
    industry: text('industry').notNull(), // e.g. 'plumbing'
    address: text('address'),
    city: text('city'),
    state: text('state'), // US 2-letter
    zip: text('zip'),
    phone: text('phone'),
    email: text('email'),
    website_url: text('website_url'),
    source: text('source').notNull(), // e.g. 'google_maps', 'yelp', 'manual'
    source_url: text('source_url'),
    rating: numeric('rating', { precision: 2, scale: 1 }),
    review_count: integer('review_count'),
    business_description: text('business_description'),
    services: jsonb('services').$type<string[]>(),
    service_area: jsonb('service_area').$type<string[]>(),
    hours: jsonb('hours').$type<Record<string, unknown>>(),
    business_status: businessOperationalStatus('business_status').default('UNKNOWN'),
    decision_maker_name: text('decision_maker_name'),
    decision_maker_role: text('decision_maker_role'),
    contactability_score: integer('contactability_score'),
    provenance: jsonb('provenance').$type<Provenance>(),
    lifecycle_state: leadLifecycleState('lifecycle_state').default('DISCOVERED').notNull(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_businesses_lifecycle_state').on(t.lifecycle_state),
    index('idx_businesses_state_city').on(t.state, t.city),
    index('idx_businesses_city_state_zip').on(t.city, t.state, t.zip),
    index('idx_businesses_source').on(t.source),
    index('idx_businesses_industry').on(t.industry),
    index('idx_businesses_zip').on(t.zip),
    check('chk_businesses_contactability', sql`${t.contactability_score} BETWEEN 0 AND 100 OR ${t.contactability_score} IS NULL`),
    check('chk_businesses_rating', sql`${t.rating} BETWEEN 0 AND 5 OR ${t.rating} IS NULL`),
  ],
);

/* ============================================================================
 * 2. CONTACTS — people at a business
 * ========================================================================== */

export const contacts = pgTable(
  'contacts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    role: text('role'),
    email: text('email'),
    phone: text('phone'),
    source: text('source'),
    verified_at: timestamp('verified_at', { withTimezone: true }),
    contactability_score: integer('contactability_score'),
    status: contactStatus('status').default('ACTIVE').notNull(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_contacts_business_id').on(t.business_id),
    index('idx_contacts_email').on(t.email),
    index('idx_contacts_status').on(t.status),
    check('chk_contacts_contactability', sql`${t.contactability_score} BETWEEN 0 AND 100 OR ${t.contactability_score} IS NULL`),
  ],
);

/* ============================================================================
 * 3. WEBSITES — discovered/scraped sites belonging to a business
 * ========================================================================== */

export const websites = pgTable(
  'websites',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id').references(() => businesses.id, { onDelete: 'set null' }),
    url: text('url').notNull(),
    status: websiteStatus('status').default('DISCOVERED').notNull(),
    http_status: integer('http_status'),
    domain: text('domain'),
    discovered_at: timestamp('discovered_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_websites_business_id').on(t.business_id),
    index('idx_websites_status').on(t.status),
    unique('u_websites_url').on(t.url),
  ],
);

/* ============================================================================
 * 4. WEBSITE_ANALYSES — results of the website-quality analysis for a site
 * ========================================================================== */

export const websiteAnalyses = pgTable(
  'website_analyses',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    website_id: uuid('website_id')
      .notNull()
      .references(() => websites.id, { onDelete: 'cascade' }),
    website_quality_score: integer('website_quality_score'),
    classification: websiteClassification('classification').notNull(),
    category_scores: jsonb('category_scores').$type<CategoryScores>(),
    test_results: jsonb('test_results').$type<Record<string, unknown>>(),
    evidence: jsonb('evidence').$type<Record<string, unknown>>(),
    critical_failures: jsonb('critical_failures').$type<unknown[]>(),
    analysis_version: uuid('analysis_version').references(() => scoringVersions.id, { onDelete: 'restrict' }),
    analyzed_at: timestamp('analyzed_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('idx_website_analyses_website_id').on(t.website_id),
    index('idx_website_analyses_analyzed_at').on(t.analyzed_at),
    check('chk_website_analyses_score', sql`${t.website_quality_score} BETWEEN 0 AND 100 OR ${t.website_quality_score} IS NULL`),
  ],
);

/* ============================================================================
 * 5. LEAD_SCORES — computed scores for a business/lead
 * ========================================================================== */

export const leadScores = pgTable(
  'lead_scores',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    website_quality_score: integer('website_quality_score'),
    business_opportunity_score: integer('business_opportunity_score'),
    market_fit_score: numeric('market_fit_score', { precision: 5, scale: 2 }),
    lead_priority_score: numeric('lead_priority_score', { precision: 5, scale: 2 }),
    classification: leadClassification('classification'),
    formula_fields: jsonb('formula_fields').$type<FormulaFields>(),
    scoring_version: uuid('scoring_version').references(() => scoringVersions.id, { onDelete: 'restrict' }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('idx_lead_scores_business_id').on(t.business_id),
    index('idx_lead_scores_created_at').on(t.created_at),
    index('idx_lead_scores_classification').on(t.classification),
    index('idx_lead_scores_priority').on(t.lead_priority_score),
    check('chk_lead_scores_wsq', sql`${t.website_quality_score} BETWEEN 0 AND 100 OR ${t.website_quality_score} IS NULL`),
    check('chk_lead_scores_bos', sql`${t.business_opportunity_score} BETWEEN 0 AND 100 OR ${t.business_opportunity_score} IS NULL`),
    check('chk_lead_scores_market_fit', sql`${t.market_fit_score} BETWEEN 0 AND 100 OR ${t.market_fit_score} IS NULL`),
    check('chk_lead_scores_priority', sql`${t.lead_priority_score} BETWEEN 0 AND 100 OR ${t.lead_priority_score} IS NULL`),
  ],
);

/* ============================================================================
 * 6. DEMOS — personalized demo websites served during outreach
 * ========================================================================== */

export const demos = pgTable(
  'demos',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id').references(() => businesses.id, { onDelete: 'set null' }),
    template_id: uuid('template_id').references(() => templates.id, { onDelete: 'set null' }),
    status: demoStatus('status').default('GENERATING').notNull(),
    demo_url: text('demo_url'),
    design_config: jsonb('design_config').$type<Record<string, unknown>>(),
    content_payload: jsonb('content_payload').$type<Record<string, unknown>>(),
    version: integer('version').default(1),
    qa_results: jsonb('qa_results').$type<Record<string, unknown>>(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_demos_business_id').on(t.business_id),
    index('idx_demos_status').on(t.status),
    index('idx_demos_template_id').on(t.template_id),
  ],
);

/* ============================================================================
 * 7. OUTREACH_CAMPAIGNS — one campaign = one audience query + template + limits
 * ========================================================================== */

export const outreachCampaigns = pgTable(
  'outreach_campaigns',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    status: campaignStatus('status').default('DRAFT').notNull(),
    audience_query: jsonb('audience_query').$type<Record<string, unknown>>(),
    email_template_id: uuid('email_template_id').references(() => templates.id, { onDelete: 'set null' }),
    daily_limit: integer('daily_limit'),
    start_date: date('start_date'),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_outreach_campaigns_status').on(t.status),
    check('chk_outreach_campaigns_daily_limit', sql`${t.daily_limit} > 0 OR ${t.daily_limit} IS NULL`),
  ],
);

/* ============================================================================
 * 8. OUTREACH_MESSAGES — individual sent/queued emails
 * ========================================================================== */

export const outreachMessages = pgTable(
  'outreach_messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    campaign_id: uuid('campaign_id').references(() => outreachCampaigns.id, { onDelete: 'set null' }),
    contact_id: uuid('contact_id').references(() => contacts.id, { onDelete: 'cascade' }),
    status: messageStatus('status').default('PENDING').notNull(),
    subject: text('subject'),
    body: text('body'),
    sent_at: timestamp('sent_at', { withTimezone: true }),
    message_id_external: text('message_id_external'),
    opened_at: timestamp('opened_at', { withTimezone: true }),
    clicked_at: timestamp('clicked_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_outreach_messages_business_id').on(t.business_id),
    index('idx_outreach_messages_campaign_id').on(t.campaign_id),
    index('idx_outreach_messages_status').on(t.status),
    index('idx_outreach_messages_contact_id').on(t.contact_id),
  ],
);

/* ============================================================================
 * 9. FOLLOWUPS — scheduled/sent follow-up messages tied to an initial message
 * ========================================================================== */

export const followups = pgTable(
  'followups',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    outreach_message_id: uuid('outreach_message_id')
      .notNull()
      .references(() => outreachMessages.id, { onDelete: 'cascade' }),
    sequence_step: integer('sequence_step'),
    scheduled_at: timestamp('scheduled_at', { withTimezone: true }),
    sent_at: timestamp('sent_at', { withTimezone: true }),
    status: followupStatus('status').default('PENDING').notNull(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_followups_outreach_message_id').on(t.outreach_message_id),
    index('idx_followups_status_scheduled_at').on(t.status, t.scheduled_at),
  ],
);

/* ============================================================================
 * 10. CONVERSATIONS — reply threads per business/contact
 * ========================================================================== */

export const conversations = pgTable(
  'conversations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    contact_id: uuid('contact_id').references(() => contacts.id, { onDelete: 'cascade' }),
    status: conversationStatus('status').default('OPEN').notNull(),
    last_message_at: timestamp('last_message_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_conversations_business_id').on(t.business_id),
    index('idx_conversations_status').on(t.status),
  ],
);

/* ============================================================================
 * 11. CONVERSATION_MESSAGES — individual messages inside a conversation
 * ========================================================================== */

export const conversationMessages = pgTable(
  'conversation_messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    conversation_id: uuid('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    direction: messageDirection('direction').notNull(),
    classification: replyClassification('classification'),
    classification_confidence: numeric('classification_confidence', { precision: 4, scale: 3 }),
    body: text('body').notNull(),
    received_at: timestamp('received_at', { withTimezone: true }),
    sent_at: timestamp('sent_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('idx_conversation_messages_conversation_id').on(t.conversation_id),
    check('chk_conversation_messages_conf', sql`${t.classification_confidence} BETWEEN 0 AND 1 OR ${t.classification_confidence} IS NULL`),
  ],
);

/* ============================================================================
 * 12. SALES_OPPORTUNITIES — qualified deals moving through the sales motion
 * ========================================================================== */

export const salesOpportunities = pgTable(
  'sales_opportunities',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    customer_id: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    status: opportunityStatus('status').default('OPEN').notNull(),
    source_lead_id: uuid('source_lead_id').references(() => businesses.id, { onDelete: 'set null' }),
    demo_url: text('demo_url'),
    value_estimate_cents: integer('value_estimate_cents'),
    won_at: timestamp('won_at', { withTimezone: true }),
    lost_at: timestamp('lost_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_sales_opportunities_status').on(t.status),
    index('idx_sales_opportunities_business_id').on(t.business_id),
    index('idx_sales_opportunities_customer_id').on(t.customer_id),
  ],
);

/* ============================================================================
 * 13. CUSTOMERS — businesses that bought
 * ========================================================================== */

export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id').references(() => businesses.id, { onDelete: 'set null' }),
    email: text('email').notNull(),
    name: text('name').notNull(),
    status: customerStatus('status').default('ACTIVE').notNull(),
    billing_email: text('billing_email'),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [unique('u_customers_business_id').on(t.business_id)],
);

/* ============================================================================
 * 14. CUSTOMER_ONBOARDING — collecting the info needed to build the site
 * ========================================================================== */

export const customerOnboarding = pgTable(
  'customer_onboarding',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customer_id: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    status: onboardingStatus('status').default('PENDING').notNull(),
    requested_fields: jsonb('requested_fields').$type<string[]>(),
    collected_fields: jsonb('collected_fields').$type<Record<string, unknown>>(),
    onboarding_form_url: text('onboarding_form_url'),
    completed_at: timestamp('completed_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    unique('u_customer_onboarding_customer_id').on(t.customer_id),
    index('idx_customer_onboarding_status').on(t.status),
  ],
);

/* ============================================================================
 * 15. PRODUCTION_WEBSITES — the real site delivered to a customer
 * ========================================================================== */

export const productionWebsites = pgTable(
  'production_websites',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customer_id: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    status: productionWebsiteStatus('status').default('ONBOARDING_COMPLETE').notNull(),
    domain_id: uuid('domain_id').references(() => domains.id, { onDelete: 'set null' }),
    version: integer('version').default(1),
    url: text('url'),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [index('idx_production_websites_customer_id').on(t.customer_id)],
);

/* ============================================================================
 * 16. WEBSITE_VERSIONS — version history for a production website
 * ========================================================================== */

export const websiteVersions = pgTable(
  'website_versions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    production_website_id: uuid('production_website_id')
      .notNull()
      .references(() => productionWebsites.id, { onDelete: 'cascade' }),
    version_number: integer('version_number').notNull(),
    status: websiteVersionStatus('status').default('DRAFT').notNull(),
    change_notes: text('change_notes'),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    unique('u_website_versions_site_number').on(t.production_website_id, t.version_number),
    index('idx_website_versions_production_website_id').on(t.production_website_id),
  ],
);

/* ============================================================================
 * 17. DOMAINS — domain lifecycle (availability → registration → use)
 * ========================================================================== */

export const domains = pgTable(
  'domains',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customer_id: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    name: text('name').notNull(),
    status: domainStatus('status').default('AVAILABLE').notNull(),
    registrar_ref: text('registrar_ref'),
    dns_verified_at: timestamp('dns_verified_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    unique('u_domains_name').on(t.name),
    index('idx_domains_customer_id').on(t.customer_id),
    index('idx_domains_status').on(t.status),
  ],
);

/* ============================================================================
 * 18. SUBSCRIPTIONS — recurring hosting/maintenance plans. NO raw card data.
 * ========================================================================== */

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customer_id: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    plan: text('plan').notNull(), // e.g. 'website_hosting_maintenance'
    status: subscriptionStatus('status').default('ACTIVE').notNull(),
    amount_cents: integer('amount_cents').notNull(),
    currency: text('currency').default('usd').notNull(),
    interval: subscriptionInterval('interval').default('MONTH').notNull(),
    current_period_start: timestamp('current_period_start', { withTimezone: true }),
    current_period_end: timestamp('current_period_end', { withTimezone: true }),
    canceled_at: timestamp('canceled_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_subscriptions_customer_id').on(t.customer_id),
    index('idx_subscriptions_status').on(t.status),
    check('chk_subscriptions_amount', sql`${t.amount_cents} > 0`),
  ],
);

/* ============================================================================
 * 19. PAYMENTS — payment attempts/records. NO raw card data anywhere.
 * ========================================================================== */

export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customer_id: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    subscription_id: uuid('subscription_id').references(() => subscriptions.id, { onDelete: 'set null' }),
    status: paymentStatus('status').default('PENDING').notNull(),
    amount_cents: integer('amount_cents').notNull(),
    currency: text('currency').default('usd').notNull(),
    external_ref: text('external_ref'),
    paid_at: timestamp('paid_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_payments_customer_id').on(t.customer_id),
    index('idx_payments_status').on(t.status),
    unique('u_payments_external_ref').on(t.external_ref),
    check('chk_payments_amount', sql`${t.amount_cents} > 0`),
  ],
);

/* ============================================================================
 * 20. TASKS — async job queue (crawl, generate, deploy, ...). Polymorphic.
 * ========================================================================== */

export const tasks = pgTable(
  'tasks',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    entity_type: text('entity_type').notNull(), // e.g. 'business', 'website', 'demo'
    entity_id: uuid('entity_id').notNull(),
    type: text('type').notNull(), // e.g. 'website_crawl', 'demo_generate', 'deploy'
    status: taskStatus('status').default('PENDING').notNull(),
    attempts: integer('attempts').default(0).notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>(),
    result: jsonb('result').$type<Record<string, unknown>>(),
    scheduled_at: timestamp('scheduled_at', { withTimezone: true }),
    started_at: timestamp('started_at', { withTimezone: true }),
    finished_at: timestamp('finished_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_tasks_status_scheduled_at').on(t.status, t.scheduled_at),
    index('idx_tasks_entity').on(t.entity_type, t.entity_id),
    index('idx_tasks_type').on(t.type),
  ],
);

/* ============================================================================
 * 21. EXCEPTIONS — owner-facing attention items. Polymorphic.
 * ========================================================================== */

export const exceptions = pgTable(
  'exceptions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    entity_type: text('entity_type').notNull(),
    entity_id: uuid('entity_id'),
    priority: exceptionPriority('priority').notNull(),
    category: text('category').notNull(),
    status: exceptionStatus('status').default('OPEN').notNull(),
    message: text('message').notNull(),
    details: jsonb('details').$type<Record<string, unknown>>(),
    first_seen_at: timestamp('first_seen_at', { withTimezone: true }).defaultNow().notNull(),
    last_seen_at: timestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(),
    resolved_at: timestamp('resolved_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_exceptions_status_priority').on(t.status, t.priority),
    index('idx_exceptions_entity').on(t.entity_type, t.entity_id),
    index('idx_exceptions_first_seen_at').on(t.first_seen_at),
  ],
);

/* ============================================================================
 * 22. AUDIT_LOGS — every state transition / mutation. Append-only.
 * ========================================================================== */

export const auditLogs = pgTable(
  'audit_logs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    actor_type: auditActorType('actor_type').notNull(),
    actor_id: uuid('actor_id'),
    action: text('action').notNull(),
    entity_type: text('entity_type').notNull(),
    entity_id: uuid('entity_id').notNull(),
    before: jsonb('before').$type<Record<string, unknown>>(),
    after: jsonb('after').$type<Record<string, unknown>>(),
    source: text('source'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('idx_audit_logs_entity').on(t.entity_type, t.entity_id),
    index('idx_audit_logs_created_at').on(t.created_at),
  ],
);

/* ============================================================================
 * 23. SYSTEM_SETTINGS — every business rule lives here, never hard-coded.
 * ========================================================================== */

export const systemSettings = pgTable(
  'system_settings',
  {
    key: text('key').primaryKey(),
    value: jsonb('value').notNull(),
    type: text('type').notNull(),
    description: text('description'),
    is_feature_flag: boolean('is_feature_flag').default(false).notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    check('chk_system_settings_type', sql`${t.type} IN ('string', 'number', 'boolean', 'json', 'array')`),
  ],
);

/* ============================================================================
 * 24. SCORING_VERSIONS — versioned weights per scoring engine
 * ========================================================================== */

export const scoringVersions = pgTable(
  'scoring_versions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    score_type: scoringType('score_type').notNull(),
    version: integer('version').notNull(),
    weights: jsonb('weights').$type<Record<string, number>>().notNull(),
    description: text('description'),
    is_active: boolean('is_active').default(false).notNull(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    unique('u_scoring_versions_type_version').on(t.score_type, t.version),
    index('idx_scoring_versions_active').on(t.score_type, t.is_active),
  ],
);

/* ============================================================================
 * 25. TEMPLATES — demo / production website templates
 * ========================================================================== */

export const templates = pgTable(
  'templates',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    type: templateType('type').notNull(),
    name: text('name').notNull(),
    template_schema: jsonb('template_schema').$type<Record<string, unknown>>(),
    is_active: boolean('is_active').default(true).notNull(),
    version: integer('version').default(1).notNull(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    unique('u_templates_type_name_version').on(t.type, t.name, t.version),
  ],
);

/* ============================================================================
 * 26. METRICS — daily aggregated operational metrics
 * ========================================================================== */

export const metrics = pgTable(
  'metrics',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    metric_date: date('metric_date').notNull(),
    metric_name: text('metric_name').notNull(),
    value: numeric('value', { precision: 14, scale: 2 }).notNull(),
    dimension: jsonb('dimension').$type<Record<string, string>>().notNull().default({}),
    // Deterministic canonical form of `dimension` — jsonb's text output is
    // key-normalized/canonical in Postgres, and a generated column is the
    // migration-tool-safe way to back the required unique constraint on
    // (metric_date, metric_name, dimension). sql`` is raw passthrough, so the
    // identifier `dimension` is resolved by the database against this table.
    dimension_key: text('dimension_key').generatedAlwaysAs(sql`(dimension)::text`),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    unique('u_metrics_date_name_dim').on(t.metric_date, t.metric_name, t.dimension_key),
  ],
);

/* ============================================================================
 * 27. LEAD_STATE_HISTORY — lifecycle transition audit for businesses
 * ========================================================================== */

export const leadStateHistory = pgTable(
  'lead_state_history',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    from_state: leadLifecycleState('from_state'),
    to_state: leadLifecycleState('to_state').notNull(),
    note: text('note'),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('idx_lead_state_history_business_id').on(t.business_id),
    index('idx_lead_state_history_business_created').on(t.business_id, t.created_at),
  ],
);

/* ============================================================================
 * 28. REJECTIONS — why a lead was rejected (REJECTED / DO_NOT_CONTACT).
 * One row per (business, rejection event); the latest rows are the current
 * reason set. Kept as a real table so later analytics can aggregate rejection
 * causes without parsing state-history notes.
 * ========================================================================== */

export const rejections = pgTable(
  'rejections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    business_id: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    reason: rejectionReason('reason').notNull(),
    // Free-text detail of what triggered the rejection (rule name, observed values).
    detail: jsonb('detail').$type<Record<string, unknown>>(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('idx_rejections_business_id').on(t.business_id),
    index('idx_rejections_reason').on(t.reason),
    index('idx_rejections_created_at').on(t.created_at),
  ],
);

/* ============================================================================
 * 29. DISCOVERY_JOBS — one provider run against one ICP target
 * (industry × state, optionally city). Lifecycle: PENDING → RUNNING →
 * COMPLETED/PARTIAL/FAILED/CANCELED; retries bump `attempts` up to the
 * `discovery.max_attempts` setting and reset progress counters.
 * `params` snapshots the target + provider + the execution settings used, so a
 * retry reuses exactly what the first attempt ran with. `progress` is
 * incremented as records stream in (never fabricated — every counter moves
 * from real provider-owned events).
 * ========================================================================== */

export const discoveryJobStatus = pgEnum('discovery_job_status', [
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'PARTIAL',
  'FAILED',
  'CANCELED',
]);

/** Progress counters for a discovery job run (all start at 0). */
export type DiscoveryJobProgress = {
  records_fetched: number;
  ingested: number;
  duplicates_skipped: number;
  invalid_skipped: number;
  errors: number;
};

export const discoveryJobs = pgTable(
  'discovery_jobs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    industry: text('industry').notNull(),
    state: text('state').notNull(),
    city: text('city'),
    provider: text('provider').notNull(),
    status: discoveryJobStatus('status').default('PENDING').notNull(),
    attempts: integer('attempts').default(0).notNull(),
    params: jsonb('params').$type<Record<string, unknown>>(),
    progress: jsonb('progress').$type<DiscoveryJobProgress>().notNull().default({
      records_fetched: 0,
      ingested: 0,
      duplicates_skipped: 0,
      invalid_skipped: 0,
      errors: 0,
    }),
    error: text('error'),
    started_at: timestamp('started_at', { withTimezone: true }),
    finished_at: timestamp('finished_at', { withTimezone: true }),
    cancelled_at: timestamp('cancelled_at', { withTimezone: true }),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index('idx_discovery_jobs_status').on(t.status),
    index('idx_discovery_jobs_created_at').on(t.created_at),
    index('idx_discovery_jobs_industry_state').on(t.industry, t.state),
  ],
);

/* ============================================================================
 * 30. DISCOVERY_JOB_ERRORS — per-record failures inside a discovery job.
 * A record that fails (invalid data, insufficient contact, ingest error) gets
 * its own row so the owner can see exactly which records failed and whether a
 * retry could plausibly fix them (`retryable`).
 * ========================================================================== */

export const discoveryJobErrors = pgTable(
  'discovery_job_errors',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    job_id: uuid('job_id')
      .notNull()
      .references(() => discoveryJobs.id, { onDelete: 'cascade' }),
    business_name: text('business_name'),
    message: text('message').notNull(),
    retryable: boolean('retryable').default(false).notNull(),
    category: text('category'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>(),
    created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('idx_discovery_job_errors_job_id').on(t.job_id),
  ],
);